//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.19 at 08:23:03 AM CET 
//


package se.kth.speech.hat.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
 *         &lt;element name="tracks">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="track" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
 *                             &lt;element name="sources">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="source" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="channel" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                                               &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}float" default="0.0" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="segments" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="segment" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
 *                             &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}transcription" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{http://www.speech.kth.se/higgins/2005/annotation/}startend"/>
 *                           &lt;attribute name="track" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "features",
    "tracks",
    "segments"
})
@XmlRootElement(name = "annotation")
public class Annotation {

    protected Features features;
    @XmlElement(required = true)
    protected Annotation.Tracks tracks;
    protected Annotation.Segments segments;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link Features }
     *     
     */
    public Features getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link Features }
     *     
     */
    public void setFeatures(Features value) {
        this.features = value;
    }

    /**
     * Gets the value of the tracks property.
     * 
     * @return
     *     possible object is
     *     {@link Annotation.Tracks }
     *     
     */
    public Annotation.Tracks getTracks() {
        return tracks;
    }

    /**
     * Sets the value of the tracks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotation.Tracks }
     *     
     */
    public void setTracks(Annotation.Tracks value) {
        this.tracks = value;
    }

    /**
     * Gets the value of the segments property.
     * 
     * @return
     *     possible object is
     *     {@link Annotation.Segments }
     *     
     */
    public Annotation.Segments getSegments() {
        return segments;
    }

    /**
     * Sets the value of the segments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotation.Segments }
     *     
     */
    public void setSegments(Annotation.Segments value) {
        this.segments = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="segment" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
     *                   &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}transcription" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{http://www.speech.kth.se/higgins/2005/annotation/}startend"/>
     *                 &lt;attribute name="track" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "segment"
    })
    public static class Segments {

        protected List<Annotation.Segments.Segment> segment;
        @XmlAttribute(name = "offset")
        protected Float offset;

        /**
         * Gets the value of the segment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the segment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Annotation.Segments.Segment }
         * 
         * 
         */
        public List<Annotation.Segments.Segment> getSegment() {
            if (segment == null) {
                segment = new ArrayList<Annotation.Segments.Segment>();
            }
            return this.segment;
        }

        /**
         * Gets the value of the offset property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getOffset() {
            return offset;
        }

        /**
         * Sets the value of the offset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setOffset(Float value) {
            this.offset = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
         *         &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}transcription" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{http://www.speech.kth.se/higgins/2005/annotation/}startend"/>
         *       &lt;attribute name="track" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "features",
            "transcription"
        })
        public static class Segment {

            protected Features features;
            protected Transcription transcription;
            @XmlAttribute(name = "track", required = true)
            protected String track;
            @XmlAttribute(name = "id", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;
            @XmlAttribute(name = "source", required = true)
            protected String source;
            @XmlAttribute(name = "start")
            protected Float start;
            @XmlAttribute(name = "end")
            protected Float end;

            /**
             * Gets the value of the features property.
             * 
             * @return
             *     possible object is
             *     {@link Features }
             *     
             */
            public Features getFeatures() {
                return features;
            }

            /**
             * Sets the value of the features property.
             * 
             * @param value
             *     allowed object is
             *     {@link Features }
             *     
             */
            public void setFeatures(Features value) {
                this.features = value;
            }

            /**
             * Gets the value of the transcription property.
             * 
             * @return
             *     possible object is
             *     {@link Transcription }
             *     
             */
            public Transcription getTranscription() {
                return transcription;
            }

            /**
             * Sets the value of the transcription property.
             * 
             * @param value
             *     allowed object is
             *     {@link Transcription }
             *     
             */
            public void setTranscription(Transcription value) {
                this.transcription = value;
            }

            /**
             * Gets the value of the track property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTrack() {
                return track;
            }

            /**
             * Sets the value of the track property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTrack(String value) {
                this.track = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSource() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSource(String value) {
                this.source = value;
            }

            /**
             * Gets the value of the start property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getStart() {
                return start;
            }

            /**
             * Sets the value of the start property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setStart(Float value) {
                this.start = value;
            }

            /**
             * Gets the value of the end property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getEnd() {
                return end;
            }

            /**
             * Sets the value of the end property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setEnd(Float value) {
                this.end = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="track" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
     *                   &lt;element name="sources">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="source" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="channel" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *                                     &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}float" default="0.0" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "track"
    })
    public static class Tracks {

        @XmlElement(required = true)
        protected List<Annotation.Tracks.Track> track;

        /**
         * Gets the value of the track property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the track property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTrack().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Annotation.Tracks.Track }
         * 
         * 
         */
        public List<Annotation.Tracks.Track> getTrack() {
            if (track == null) {
                track = new ArrayList<Annotation.Tracks.Track>();
            }
            return this.track;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
         *         &lt;element name="sources">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="source" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="channel" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
         *                           &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}float" default="0.0" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "features",
            "sources"
        })
        public static class Track {

            protected Features features;
            @XmlElement(required = true)
            protected Annotation.Tracks.Track.Sources sources;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the features property.
             * 
             * @return
             *     possible object is
             *     {@link Features }
             *     
             */
            public Features getFeatures() {
                return features;
            }

            /**
             * Sets the value of the features property.
             * 
             * @param value
             *     allowed object is
             *     {@link Features }
             *     
             */
            public void setFeatures(Features value) {
                this.features = value;
            }

            /**
             * Gets the value of the sources property.
             * 
             * @return
             *     possible object is
             *     {@link Annotation.Tracks.Track.Sources }
             *     
             */
            public Annotation.Tracks.Track.Sources getSources() {
                return sources;
            }

            /**
             * Sets the value of the sources property.
             * 
             * @param value
             *     allowed object is
             *     {@link Annotation.Tracks.Track.Sources }
             *     
             */
            public void setSources(Annotation.Tracks.Track.Sources value) {
                this.sources = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="source" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="channel" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
             *                 &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}float" default="0.0" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "source"
            })
            public static class Sources {

                @XmlElement(required = true)
                protected List<Annotation.Tracks.Track.Sources.Source> source;

                /**
                 * Gets the value of the source property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the source property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getSource().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Annotation.Tracks.Track.Sources.Source }
                 * 
                 * 
                 */
                public List<Annotation.Tracks.Track.Sources.Source> getSource() {
                    if (source == null) {
                        source = new ArrayList<Annotation.Tracks.Track.Sources.Source>();
                    }
                    return this.source;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element ref="{http://www.speech.kth.se/higgins/2005/annotation/}features" minOccurs="0"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="channel" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
                 *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}float" default="0.0" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "features"
                })
                public static class Source {

                    protected Features features;
                    @XmlAttribute(name = "href", required = true)
                    protected String href;
                    @XmlAttribute(name = "id", required = true)
                    protected String id;
                    @XmlAttribute(name = "channel")
                    protected Integer channel;
                    @XmlAttribute(name = "offset")
                    protected Float offset;

                    /**
                     * Gets the value of the features property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Features }
                     *     
                     */
                    public Features getFeatures() {
                        return features;
                    }

                    /**
                     * Sets the value of the features property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Features }
                     *     
                     */
                    public void setFeatures(Features value) {
                        this.features = value;
                    }

                    /**
                     * Gets the value of the href property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getHref() {
                        return href;
                    }

                    /**
                     * Sets the value of the href property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setHref(String value) {
                        this.href = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setId(String value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the channel property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public int getChannel() {
                        if (channel == null) {
                            return  0;
                        } else {
                            return channel;
                        }
                    }

                    /**
                     * Sets the value of the channel property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setChannel(Integer value) {
                        this.channel = value;
                    }

                    /**
                     * Gets the value of the offset property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Float }
                     *     
                     */
                    public float getOffset() {
                        if (offset == null) {
                            return  0.0F;
                        } else {
                            return offset;
                        }
                    }

                    /**
                     * Sets the value of the offset property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Float }
                     *     
                     */
                    public void setOffset(Float value) {
                        this.offset = value;
                    }

                }

            }

        }

    }

}
