//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.19 at 08:23:03 AM CET 
//


package se.kth.speech.hat.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.kth.speech.hat.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.kth.speech.hat.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Features }
     * 
     */
    public Features createFeatures() {
        return new Features();
    }

    /**
     * Create an instance of {@link se.kth.speech.hat.xsd.Annotation }
     * 
     */
    public se.kth.speech.hat.xsd.Annotation createAnnotation() {
        return new se.kth.speech.hat.xsd.Annotation();
    }

    /**
     * Create an instance of {@link Transcription }
     * 
     */
    public Transcription createTranscription() {
        return new Transcription();
    }

    /**
     * Create an instance of {@link Annotations }
     * 
     */
    public Annotations createAnnotations() {
        return new Annotations();
    }

    /**
     * Create an instance of {@link se.kth.speech.hat.xsd.Annotation.Segments }
     * 
     */
    public se.kth.speech.hat.xsd.Annotation.Segments createAnnotationSegments() {
        return new se.kth.speech.hat.xsd.Annotation.Segments();
    }

    /**
     * Create an instance of {@link se.kth.speech.hat.xsd.Annotation.Tracks }
     * 
     */
    public se.kth.speech.hat.xsd.Annotation.Tracks createAnnotationTracks() {
        return new se.kth.speech.hat.xsd.Annotation.Tracks();
    }

    /**
     * Create an instance of {@link se.kth.speech.hat.xsd.Annotation.Tracks.Track }
     * 
     */
    public se.kth.speech.hat.xsd.Annotation.Tracks.Track createAnnotationTracksTrack() {
        return new se.kth.speech.hat.xsd.Annotation.Tracks.Track();
    }

    /**
     * Create an instance of {@link se.kth.speech.hat.xsd.Annotation.Tracks.Track.Sources }
     * 
     */
    public se.kth.speech.hat.xsd.Annotation.Tracks.Track.Sources createAnnotationTracksTrackSources() {
        return new se.kth.speech.hat.xsd.Annotation.Tracks.Track.Sources();
    }

    /**
     * Create an instance of {@link Features.Feature }
     * 
     */
    public Features.Feature createFeaturesFeature() {
        return new Features.Feature();
    }

    /**
     * Create an instance of {@link se.kth.speech.hat.xsd.Segment }
     * 
     */
    public se.kth.speech.hat.xsd.Segment createSegment() {
        return new se.kth.speech.hat.xsd.Segment();
    }

    /**
     * Create an instance of {@link Transcription.T }
     * 
     */
    public Transcription.T createTranscriptionT() {
        return new Transcription.T();
    }

    /**
     * Create an instance of {@link Annotations.Annotation }
     * 
     */
    public Annotations.Annotation createAnnotationsAnnotation() {
        return new Annotations.Annotation();
    }

    /**
     * Create an instance of {@link se.kth.speech.hat.xsd.Annotation.Segments.Segment }
     * 
     */
    public se.kth.speech.hat.xsd.Annotation.Segments.Segment createAnnotationSegmentsSegment() {
        return new se.kth.speech.hat.xsd.Annotation.Segments.Segment();
    }

    /**
     * Create an instance of {@link se.kth.speech.hat.xsd.Annotation.Tracks.Track.Sources.Source }
     * 
     */
    public se.kth.speech.hat.xsd.Annotation.Tracks.Track.Sources.Source createAnnotationTracksTrackSourcesSource() {
        return new se.kth.speech.hat.xsd.Annotation.Tracks.Track.Sources.Source();
    }

}
