//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.19 at 08:23:03 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.speech.kth.se/higgins/2005/annotation/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.kth.speech.hat.xsd;
